pub const AALOAD: u8 = 0x32;
pub const AASTORE: u8 = 0x53;
pub const ACONST_NULL: u8 = 0x01;
pub const ALOAD: u8 = 0x19;
pub const ALOAD_0: u8 = 0x2a;
pub const ALOAD_1: u8 = 0x2b;
pub const ALOAD_2: u8 = 0x2c;
pub const ALOAD_3: u8 = 0x2d;
pub const ANEWARRAY: u8 = 0xbd;
pub const ARETURN: u8 = 0xb0;
pub const ARRAYLENGTH: u8 = 0xbe;
pub const ASTORE: u8 = 0x3a;
pub const ASTORE_0: u8 = 0x4b;
pub const ASTORE_1: u8 = 0x4c;
pub const ASTORE_2: u8 = 0x4d;
pub const ASTORE_3: u8 = 0x4e;
pub const ATHROW: u8 = 0xbf;
pub const BALOAD: u8 = 0x33;
pub const BASTORE: u8 = 0x54;
pub const BIPUSH: u8 = 0x10;
pub const BREAKPOINT: u8 = 0xca;
pub const CALOAD: u8 = 0x34;
pub const CASTORE: u8 = 0x55;
pub const CHECKCAST: u8 = 0xc0;
pub const D2F: u8 = 0x90;
pub const D2I: u8 = 0x8e;
pub const D2L: u8 = 0x8f;
pub const DADD: u8 = 0x63;
pub const DALOAD: u8 = 0x31;
pub const DASTORE: u8 = 0x52;
pub const DCMPG: u8 = 0x98;
pub const DCMPL: u8 = 0x97;
pub const DCONST_0: u8 = 0x0e;
pub const DCONST_1: u8 = 0x0f;
pub const DDIV: u8 = 0x6f;
pub const DLOAD: u8 = 0x18;
pub const DLOAD_0: u8 = 0x26;
pub const DLOAD_1: u8 = 0x27;
pub const DLOAD_2: u8 = 0x28;
pub const DLOAD_3: u8 = 0x29;
pub const DMUL: u8 = 0x6b;
pub const DNEG: u8 = 0x77;
pub const DREM: u8 = 0x73;
pub const DRETURN: u8 = 0xaf;
pub const DSTORE: u8 = 0x39;
pub const DSTORE_0: u8 = 0x47;
pub const DSTORE_1: u8 = 0x48;
pub const DSTORE_2: u8 = 0x49;
pub const DSTORE_3: u8 = 0x4a;
pub const DSUB: u8 = 0x67;
pub const DUP: u8 = 0x59;
pub const DUP_X1: u8 = 0x5a;
pub const DUP_X2: u8 = 0x5b;
pub const DUP2: u8 = 0x5c;
pub const DUP2_X1: u8 = 0x5d;
pub const DUP2_X2: u8 = 0x5e;
pub const F2D: u8 = 0x8d;
pub const F2I: u8 = 0x8b;
pub const F2L: u8 = 0x8c;
pub const FADD: u8 = 0x62;
pub const FALOAD: u8 = 0x30;
pub const FASTORE: u8 = 0x51;
pub const FCMPG: u8 = 0x96;
pub const FCMPL: u8 = 0x95;
pub const FCONST_0: u8 = 0x0b;
pub const FCONST_1: u8 = 0x0c;
pub const FCONST_2: u8 = 0x0d;
pub const FDIV: u8 = 0x6e;
pub const FLOAD: u8 = 0x17;
pub const FLOAD_0: u8 = 0x22;
pub const FLOAD_1: u8 = 0x23;
pub const FLOAD_2: u8 = 0x24;
pub const FLOAD_3: u8 = 0x25;
pub const FMUL: u8 = 0x6a;
pub const FNEG: u8 = 0x76;
pub const FREM: u8 = 0x72;
pub const FRETURN: u8 = 0xae;
pub const FSTORE: u8 = 0x38;
pub const FSTORE_0: u8 = 0x43;
pub const FSTORE_1: u8 = 0x44;
pub const FSTORE_2: u8 = 0x45;
pub const FSTORE_3: u8 = 0x46;
pub const FSUB: u8 = 0x66;
pub const GETFIELD: u8 = 0xb4;
pub const GETSTATIC: u8 = 0xb2;
pub const GOTO: u8 = 0xa7;
pub const GOTO_W: u8 = 0xc8;
pub const I2B: u8 = 0x91;
pub const I2C: u8 = 0x92;
pub const I2D: u8 = 0x87;
pub const I2F: u8 = 0x86;
pub const I2L: u8 = 0x85;
pub const I2S: u8 = 0x93;
pub const IADD: u8 = 0x60;
pub const IALOAD: u8 = 0x2e;
pub const IAND: u8 = 0x7e;
pub const IASTORE: u8 = 0x4f;
pub const ICONST_M1: u8 = 0x02;
pub const ICONST_0: u8 = 0x03;
pub const ICONST_1: u8 = 0x04;
pub const ICONST_2: u8 = 0x05;
pub const ICONST_3: u8 = 0x06;
pub const ICONST_4: u8 = 0x07;
pub const ICONST_5: u8 = 0x08;
pub const IDIV: u8 = 0x6c;
pub const IF_ACMPEQ: u8 = 0xa5;
pub const IF_ACMPNE: u8 = 0xa6;
pub const IF_ICMPEQ: u8 = 0x9f;
pub const IF_ICMPGE: u8 = 0xa2;
pub const IF_ICMPGT: u8 = 0xa3;
pub const IF_ICMPLE: u8 = 0xa4;
pub const IF_ICMPLT: u8 = 0xa1;
pub const IF_ICMPNE: u8 = 0xa0;
pub const IFEQ: u8 = 0x99;
pub const IFGE: u8 = 0x9c;
pub const IFGT: u8 = 0x9d;
pub const IFLE: u8 = 0x9e;
pub const IFLT: u8 = 0x9b;
pub const IFNE: u8 = 0x9a;
pub const IFNONNULL: u8 = 0xc7;
pub const IFNULL: u8 = 0xc6;
pub const IINC: u8 = 0x84;
pub const ILOAD: u8 = 0x15;
pub const ILOAD_0: u8 = 0x1a;
pub const ILOAD_1: u8 = 0x1b;
pub const ILOAD_2: u8 = 0x1c;
pub const ILOAD_3: u8 = 0x1d;
pub const IMPDEP1: u8 = 0xfe;
pub const IMPDEP2: u8 = 0xff;
pub const IMUL: u8 = 0x68;
pub const INEG: u8 = 0x74;
pub const INSTANCEOF: u8 = 0xc1;
pub const INVOKEDYNAMIC: u8 = 0xba;
pub const INVOKEINTERFACE: u8 = 0xb9;
pub const INVOKESPECIAL: u8 = 0xb7;
pub const INVOKESTATIC: u8 = 0xb8;
pub const INVOKEVIRTUAL: u8 = 0xb6;
pub const IOR: u8 = 0x80;
pub const IREM: u8 = 0x70;
pub const IRETURN: u8 = 0xac;
pub const ISHL: u8 = 0x78;
pub const ISHR: u8 = 0x7a;
pub const ISTORE: u8 = 0x36;
pub const ISTORE_0: u8 = 0x3b;
pub const ISTORE_1: u8 = 0x3c;
pub const ISTORE_2: u8 = 0x3d;
pub const ISTORE_3: u8 = 0x3e;
pub const ISUB: u8 = 0x64;
pub const IUSHR: u8 = 0x7c;
pub const IXOR: u8 = 0x82;
pub const JSR: u8 = 0xa8;
pub const JSR_W: u8 = 0xc9;
pub const L2D: u8 = 0x8a;
pub const L2F: u8 = 0x89;
pub const L2I: u8 = 0x88;
pub const LADD: u8 = 0x61;
pub const LALOAD: u8 = 0x2f;
pub const LAND: u8 = 0x7f;
pub const LASTORE: u8 = 0x50;
pub const LCMP: u8 = 0x94;
pub const LCONST_0: u8 = 0x09;
pub const LCONST_1: u8 = 0x0a;
pub const LDC: u8 = 0x12;
pub const LDC_W: u8 = 0x13;
pub const LDC2_W: u8 = 0x14;
pub const LDIV: u8 = 0x6d;
pub const LLOAD: u8 = 0x16;
pub const LLOAD_0: u8 = 0x1e;
pub const LLOAD_1: u8 = 0x1f;
pub const LLOAD_2: u8 = 0x20;
pub const LLOAD_3: u8 = 0x21;
pub const LMUL: u8 = 0x69;
pub const LNEG: u8 = 0x75;
pub const LOOKUPSWITCH: u8 = 0xab;
pub const LOR: u8 = 0x81;
pub const LREM: u8 = 0x71;
pub const LRETURN: u8 = 0xad;
pub const LSHL: u8 = 0x79;
pub const LSHR: u8 = 0x7b;
pub const LSTORE: u8 = 0x37;
pub const LSTORE_0: u8 = 0x3f;
pub const LSTORE_1: u8 = 0x40;
pub const LSTORE_2: u8 = 0x41;
pub const LSTORE_3: u8 = 0x42;
pub const LSUB: u8 = 0x65;
pub const LUSHR: u8 = 0x7d;
pub const LXOR: u8 = 0x83;
pub const MONITORENTER: u8 = 0xc2;
pub const MONITOREXIT: u8 = 0xc3;
pub const MULTIANEWARRAY: u8 = 0xc5;
pub const NEW: u8 = 0xbb;
pub const NEWARRAY: u8 = 0xbc;
pub const NOP: u8 = 0x00;
pub const POP: u8 = 0x57;
pub const POP2: u8 = 0x58;
pub const PUTFIELD: u8 = 0xb5;
pub const PUTSTATIC: u8 = 0xb3;
pub const RET: u8 = 0xa9;
pub const RETURN: u8 = 0xb1;
pub const SALOAD: u8 = 0x35;
pub const SASTORE: u8 = 0x56;
pub const SIPUSH: u8 = 0x11;
pub const SWAP: u8 = 0x5f;
pub const TABLESWITCH: u8 = 0xaa;
pub const WIDE: u8 = 0xc4;

pub fn opcode_to_name(opcode: u8) -> Option<&'static str> {
    match opcode {
        AALOAD => Some("AALOAD"),
        AASTORE => Some("AASTORE"),
        ACONST_NULL => Some("ACONST_NULL"),
        ALOAD => Some("ALOAD"),
        ALOAD_0 => Some("ALOAD_0"),
        ALOAD_1 => Some("ALOAD_1"),
        ALOAD_2 => Some("ALOAD_2"),
        ALOAD_3 => Some("ALOAD_3"),
        ANEWARRAY => Some("ANEWARRAY"),
        ARETURN => Some("ARETURN"),
        ARRAYLENGTH => Some("ARRAYLENGTH"),
        ASTORE => Some("ASTORE"),
        ASTORE_0 => Some("ASTORE_0"),
        ASTORE_1 => Some("ASTORE_1"),
        ASTORE_2 => Some("ASTORE_2"),
        ASTORE_3 => Some("ASTORE_3"),
        ATHROW => Some("ATHROW"),
        BALOAD => Some("BALOAD"),
        BASTORE => Some("BASTORE"),
        BIPUSH => Some("BIPUSH"),
        BREAKPOINT => Some("BREAKPOINT"),
        CALOAD => Some("CALOAD"),
        CASTORE => Some("CASTORE"),
        CHECKCAST => Some("CHECKCAST"),
        D2F => Some("D2F"),
        D2I => Some("D2I"),
        D2L => Some("D2L"),
        DADD => Some("DADD"),
        DALOAD => Some("DALOAD"),
        DASTORE => Some("DASTORE"),
        DCMPG => Some("DCMPG"),
        DCMPL => Some("DCMPL"),
        DCONST_0 => Some("DCONST_0"),
        DCONST_1 => Some("DCONST_1"),
        DDIV => Some("DDIV"),
        DLOAD => Some("DLOAD"),
        DLOAD_0 => Some("DLOAD_0"),
        DLOAD_1 => Some("DLOAD_1"),
        DLOAD_2 => Some("DLOAD_2"),
        DLOAD_3 => Some("DLOAD_3"),
        DMUL => Some("DMUL"),
        DNEG => Some("DNEG"),
        DREM => Some("DREM"),
        DRETURN => Some("DRETURN"),
        DSTORE => Some("DSTORE"),
        DSTORE_0 => Some("DSTORE_0"),
        DSTORE_1 => Some("DSTORE_1"),
        DSTORE_2 => Some("DSTORE_2"),
        DSTORE_3 => Some("DSTORE_3"),
        DSUB => Some("DSUB"),
        DUP => Some("DUP"),
        DUP_X1 => Some("DUP_X1"),
        DUP_X2 => Some("DUP_X2"),
        DUP2 => Some("DUP2"),
        DUP2_X1 => Some("DUP2_X1"),
        DUP2_X2 => Some("DUP2_X2"),
        F2D => Some("F2D"),
        F2I => Some("F2I"),
        F2L => Some("F2L"),
        FADD => Some("FADD"),
        FALOAD => Some("FALOAD"),
        FASTORE => Some("FASTORE"),
        FCMPG => Some("FCMPG"),
        FCMPL => Some("FCMPL"),
        FCONST_0 => Some("FCONST_0"),
        FCONST_1 => Some("FCONST_1"),
        FCONST_2 => Some("FCONST_2"),
        FDIV => Some("FDIV"),
        FLOAD => Some("FLOAD"),
        FLOAD_0 => Some("FLOAD_0"),
        FLOAD_1 => Some("FLOAD_1"),
        FLOAD_2 => Some("FLOAD_2"),
        FLOAD_3 => Some("FLOAD_3"),
        FMUL => Some("FMUL"),
        FNEG => Some("FNEG"),
        FREM => Some("FREM"),
        FRETURN => Some("FRETURN"),
        FSTORE => Some("FSTORE"),
        FSTORE_0 => Some("FSTORE_0"),
        FSTORE_1 => Some("FSTORE_1"),
        FSTORE_2 => Some("FSTORE_2"),
        FSTORE_3 => Some("FSTORE_3"),
        FSUB => Some("FSUB"),
        GETFIELD => Some("GETFIELD"),
        GETSTATIC => Some("GETSTATIC"),
        GOTO => Some("GOTO"),
        GOTO_W => Some("GOTO_W"),
        I2B => Some("I2B"),
        I2C => Some("I2C"),
        I2D => Some("I2D"),
        I2F => Some("I2F"),
        I2L => Some("I2L"),
        I2S => Some("I2S"),
        IADD => Some("IADD"),
        IALOAD => Some("IALOAD"),
        IAND => Some("IAND"),
        IASTORE => Some("IASTORE"),
        ICONST_M1 => Some("ICONST_M1"),
        ICONST_0 => Some("ICONST_0"),
        ICONST_1 => Some("ICONST_1"),
        ICONST_2 => Some("ICONST_2"),
        ICONST_3 => Some("ICONST_3"),
        ICONST_4 => Some("ICONST_4"),
        ICONST_5 => Some("ICONST_5"),
        IDIV => Some("IDIV"),
        IF_ACMPEQ => Some("IF_ACMPEQ"),
        IF_ACMPNE => Some("IF_ACMPNE"),
        IF_ICMPEQ => Some("IF_ICMPEQ"),
        IF_ICMPGE => Some("IF_ICMPGE"),
        IF_ICMPGT => Some("IF_ICMPGT"),
        IF_ICMPLE => Some("IF_ICMPLE"),
        IF_ICMPLT => Some("IF_ICMPLT"),
        IF_ICMPNE => Some("IF_ICMPNE"),
        IFEQ => Some("IFEQ"),
        IFGE => Some("IFGE"),
        IFGT => Some("IFGT"),
        IFLE => Some("IFLE"),
        IFLT => Some("IFLT"),
        IFNE => Some("IFNE"),
        IFNONNULL => Some("IFNONNULL"),
        IFNULL => Some("IFNULL"),
        IINC => Some("IINC"),
        ILOAD => Some("ILOAD"),
        ILOAD_0 => Some("ILOAD_0"),
        ILOAD_1 => Some("ILOAD_1"),
        ILOAD_2 => Some("ILOAD_2"),
        ILOAD_3 => Some("ILOAD_3"),
        IMPDEP1 => Some("IMPDEP1"),
        IMPDEP2 => Some("IMPDEP2"),
        IMUL => Some("IMUL"),
        INEG => Some("INEG"),
        INSTANCEOF => Some("INSTANCEOF"),
        INVOKEDYNAMIC => Some("INVOKEDYNAMIC"),
        INVOKEINTERFACE => Some("INVOKEINTERFACE"),
        INVOKESPECIAL => Some("INVOKESPECIAL"),
        INVOKESTATIC => Some("INVOKESTATIC"),
        INVOKEVIRTUAL => Some("INVOKEVIRTUAL"),
        IOR => Some("IOR"),
        IREM => Some("IREM"),
        IRETURN => Some("IRETURN"),
        ISHL => Some("ISHL"),
        ISHR => Some("ISHR"),
        ISTORE => Some("ISTORE"),
        ISTORE_0 => Some("ISTORE_0"),
        ISTORE_1 => Some("ISTORE_1"),
        ISTORE_2 => Some("ISTORE_2"),
        ISTORE_3 => Some("ISTORE_3"),
        ISUB => Some("ISUB"),
        IUSHR => Some("IUSHR"),
        IXOR => Some("IXOR"),
        JSR => Some("JSR"),
        JSR_W => Some("JSR_W"),
        L2D => Some("L2D"),
        L2F => Some("L2F"),
        L2I => Some("L2I"),
        LADD => Some("LADD"),
        LALOAD => Some("LALOAD"),
        LAND => Some("LAND"),
        LASTORE => Some("LASTORE"),
        LCMP => Some("LCMP"),
        LCONST_0 => Some("LCONST_0"),
        LCONST_1 => Some("LCONST_1"),
        LDC => Some("LDC"),
        LDC_W => Some("LDC_W"),
        LDC2_W => Some("LDC2_W"),
        LDIV => Some("LDIV"),
        LLOAD => Some("LLOAD"),
        LLOAD_0 => Some("LLOAD_0"),
        LLOAD_1 => Some("LLOAD_1"),
        LLOAD_2 => Some("LLOAD_2"),
        LLOAD_3 => Some("LLOAD_3"),
        LMUL => Some("LMUL"),
        LNEG => Some("LNEG"),
        LOOKUPSWITCH => Some("LOOKUPSWITCH"),
        LOR => Some("LOR"),
        LREM => Some("LREM"),
        LRETURN => Some("LRETURN"),
        LSHL => Some("LSHL"),
        LSHR => Some("LSHR"),
        LSTORE => Some("LSTORE"),
        LSTORE_0 => Some("LSTORE_0"),
        LSTORE_1 => Some("LSTORE_1"),
        LSTORE_2 => Some("LSTORE_2"),
        LSTORE_3 => Some("LSTORE_3"),
        LSUB => Some("LSUB"),
        LUSHR => Some("LUSHR"),
        LXOR => Some("LXOR"),
        MONITORENTER => Some("MONITORENTER"),
        MONITOREXIT => Some("MONITOREXIT"),
        MULTIANEWARRAY => Some("MULTIANEWARRAY"),
        NEW => Some("NEW"),
        NEWARRAY => Some("NEWARRAY"),
        NOP => Some("NOP"),
        POP => Some("POP"),
        POP2 => Some("POP2"),
        PUTFIELD => Some("PUTFIELD"),
        PUTSTATIC => Some("PUTSTATIC"),
        RET => Some("RET"),
        RETURN => Some("RETURN"),
        SALOAD => Some("SALOAD"),
        SASTORE => Some("SASTORE"),
        SIPUSH => Some("SIPUSH"),
        SWAP => Some("SWAP"),
        TABLESWITCH => Some("TABLESWITCH"),
        WIDE => Some("WIDE"),
        _ => None,
    }
}
